### ISSUE TITLE
How would you connect two elemets on load

### ISSUE THREAD

**Issue by paritoshmmmec** [mrquincle/jsplumb-example#1]
How you connect two element on loading

**Comment by mrquincle** [comment]
Hi there,

The current setup is such that all the manipulation with respect to connectors is left to jsPlumb. The connections are not represented as first class citizens in an AngularJS controller. This means that we do no have to do all the stuff jsPlumb already does perfectly, like keeping track of connections and disconnections, etc. To create a solid "$scope.addConnection" function, I would go through the DOM elements and call jsPlumb.connect. If you post a code snippet of what goes wrong, I might help you go on. :-)
